# Generated by Django 2.0.1 on 2018-02-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180124_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='respuesta',
            new_name='votos',
        ),
    ]
