# Generated by Django 2.0.1 on 2018-02-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180201_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='votos',
            new_name='respuesta',
        ),
    ]
