# Generated by Django 2.0.1 on 2018-02-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_voto_votos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='votos',
        ),
    ]
